name       : anoise-media
version    : 0.0.16
release    : 1
source     :
    - https://launchpad.net/anoise/0.0.x/0.0.x/+download/anoise-media_0.0.16.tar.gz : 34db810dcab243ab2871b226da3bc6799b941671046e244ab1b73c7d6367cc85
license    : GPL-3.0
component  : multimedia.audio 
summary    : Default ambient noise files for ANoise
description: Default ambient noise files for ANoise
builddeps  : 
    - python-distutils-extra
build      : |
    %python_setup
install    : |
    %python_install
