name       : anoise-media
version    : 0.0.17
release    : 2
source     :
    - https://launchpad.net/~costales/+archive/ubuntu/anoise/+files/anoise-media_0.0.17.tar.gz : 7ad6b20438687107d850fd4bad760f103e7f2eb5ec7b1b45296ad29433cc0f36
license    : GPL-3.0
component  : multimedia.audio
summary    : Default ambient noise files for ANoise
description: Default ambient noise files for ANoise
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
build      : |
    %python3_setup
install    : |
    %python3_install
